### ISSUE TITLE
Modal API 연동 문제

### ISSUE THREAD

**Issue by ImChangGyu** [Team-Ampersand/Dotori-client#146]
## 문제 상황
<img width="1022" alt="스크린샷 2022-03-03 오후 11 09 18" src="https://user-images.githubusercontent.com/66630940/156580986-6b63542e-f822-47cc-9608-5a221f22d667.png">
위와 같이 모달을 불러오기도 전에 학년 전체 조회 시에 데이터를 미리 전부 불러옴 (이는 전체 조회에도 해당 했었던 내용)

## 해결책
조건부 렌더링을 이용하여 modalState가 true일때 렌더링 될 수 있도록 함

> 문제사항을 겪은 사람: @KimGiHong @ImChangGyu

**Comment by KimGiHong** [comment]
아 이런 방법이 있었네요 이건 바로 어떤 느낌인지 알 것 같아요

**Comment by ImChangGyu** [comment]
#149 #147  해결!
