### ISSUE TITLE
메뉴에서 커서가 보입니다.

### ISSUE THREAD

**Issue by wnstj1030** [Team-Ampersand/Dotori-client#294]
![issue](https://user-images.githubusercontent.com/103114153/165768830-9ad82cbb-5ac3-4aa3-9052-fc467e49df79.jpg)

[issue]
- menu 부분에서 커서가 보입니다.

**Comment by JeongTaehwan** [comment]
확인해본 결과, 특정 노트북의 오류 및 Chrome 오류인 것 같습니다. 해결을 할 필요가 없어보입니다.
