### ISSUE TITLE
Authorzation 네이밍 수정 부탁드립니다.

### ISSUE THREAD

**Issue by Leesin0222** [Team-Ampersand/Dotori-client#353]
![image](https://user-images.githubusercontent.com/90879448/194760649-39b0d173-ebae-41ad-b7f3-f9bc29ced2dd.png)

사진을 보면 Authorzation이라고 네이밍이 되어있는데 Authorization으로 네이밍  수정 부탁드립니다!👍

**Comment by ImChangGyu** [comment]
좋은 관심 감사드립니다
해당 이슈는 해결 하도록하겠습니다

**Comment by Leesin0222** [comment]
감사합니다💕
